[package]
name = "modalkit"
version = "0.0.1"
authors = ["Ulyssa <git@ulyssa.dev>"]
repository = "https://github.com/ulyssa/modalkit"
homepage = "https://github.com/ulyssa/modalkit"
readme = "README.md"
description = "A library for building applications that use modal editing"
license = "Apache-2.0"
edition = "2018"
exclude = [".github", "CONTRIBUTING.md"]

[dependencies]
thiserror = "1.0.30"
crossterm = "0.17"
xi-rope = "0.3.0"
bitflags = "1.2"
lazy_static = "1.4.0"
nom = "7.0.0"
regex = "1.5.4"
